variable "domain" {
  type        = string
  description = "The user-facing root domain (this is 'playfulprogramming.com' in prod)"
}

variable "host" {
  type        = string
  description = "The backend hostname that requests are proxied to"
}

variable "noindex" {
  type        = bool
  description = "Whether a noindex header should be appended to every response"
}

variable "subdomain_redirects" {
  type = map(object({
    location     = string
    preserve_url = bool
    status       = number
  }))
  description = "Map of subdomain to its redirect configuration"
  default     = {}

  validation {
    condition = alltrue([
      for redirect in values(var.subdomain_redirects) :
      contains([301, 302], redirect.status)
    ])
    error_message = "Redirect status must be either 301 or 302."
  }
}

locals {
  subdomain_redirect_hosts = {
    for subdomain, redirect in var.subdomain_redirects :
    "${subdomain}.${var.domain}" => redirect
  }
}

resource "fastly_service_vcl" "cdn" {
  activate = true
  comment  = "Managed by Tofu"
  http3    = true
  name     = "PFP Website for ${var.domain}"
  stage    = false

  domain {
    name = var.domain
  }

  dynamic "domain" {
    for_each = local.subdomain_redirect_hosts
    content {
      name = domain.key
    }
  }

  backend {
    address           = var.host
    name              = "Host 1"
    port              = 443
    prefer_ipv6       = true
    ssl_cert_hostname = var.host
    ssl_sni_hostname  = var.host
    use_ssl           = true
  }

  gzip {
    content_types = [
      "text/html",
      "application/x-javascript",
      "text/css",
      "application/javascript",
      "text/javascript",
      "application/json",
      "application/vnd.ms-fontobject",
      "application/x-font-opentype",
      "application/x-font-truetype",
      "application/x-font-ttf",
      "application/xml",
      "font/eot",
      "font/opentype",
      "font/otf",
      "image/svg+xml",
      "image/vnd.microsoft.icon",
      "text/plain",
      "text/xml",
    ]
    extensions = [
      "css",
      "js",
      "html",
      "eot",
      "ico",
      "otf",
      "ttf",
      "json",
      "svg",
    ]
    name = "Generated by default compression policy"
  }

  dynamic "header" {
    for_each = var.noindex ? [] : [1]
    content {
      action        = "set"
      destination   = "http.Playful-Enable-Discoverability"
      ignore_if_set = false
      name          = "Pass header to enable discoverability in prod"
      priority      = 100
      source        = "\"true\""
      type          = "request"
    }
  }

  dynamic "header" {
    for_each = var.noindex ? [] : [1]
    content {
      action        = "set"
      destination   = "http.Playful-Enable-Discoverability"
      ignore_if_set = false
      name          = "Pass header to enable discoverability in prod"
      priority      = 100
      source        = "\"true\""
      type          = "cache"
    }
  }

  header {
    action        = "set"
    destination   = "http.Strict-Transport-Security"
    ignore_if_set = false
    name          = "Generated by force TLS and enable HSTS"
    priority      = 100
    source        = "\"max-age=300\""
    type          = "response"
  }

  dynamic "header" {
    for_each = var.noindex ? [1] : []
    content {
      action        = "set"
      destination   = "http.X-Robots-Tag"
      ignore_if_set = false
      name          = "Prevent indexing in staging"
      priority      = 100
      source        = "\"noindex\""
      type          = "response"
    }
  }

  product_enablement {
    bot_management        = false
    brotli_compression    = false
    domain_inspector      = false
    image_optimizer       = false
    log_explorer_insights = false
    origin_inspector      = true
    websockets            = false
  }

  request_setting {
    bypass_busy_wait = false
    force_miss       = false
    force_ssl        = true
    max_stale_age    = 0
    name             = "Generated by force TLS and enable HSTS"
    timer_support    = false
  }

  snippet {
    name     = "redirects_init"
    type     = "init"
    priority = 100
    content = join("\n", concat(
      ["table redirect_locations STRING {"],
      [for host, redirect in local.subdomain_redirect_hosts : "  ${jsonencode(host)}: ${jsonencode(redirect.location)},"],
      ["}", "", "table redirect_statuses INTEGER {"],
      [for host, redirect in local.subdomain_redirect_hosts : "  ${jsonencode(host)}: ${redirect.status},"],
      ["}", "", "table redirect_preserve_urls BOOL {"],
      [for host, redirect in local.subdomain_redirect_hosts : "  ${jsonencode(host)}: ${redirect.preserve_url},"],
      ["}"],
    ))
  }

  snippet {
    name     = "redirects_recv"
    type     = "recv"
    priority = 100
    content  = <<-VCL
      if (table.contains(redirect_locations, std.tolower(req.http.host))) {
        error 618 "redirect";
      }
    VCL
  }

  snippet {
    name     = "redirects_error"
    type     = "error"
    priority = 100
    content  = <<-VCL
      if (obj.status == 618 && obj.response == "redirect") {
        set obj.status = table.lookup_integer(redirect_statuses, std.tolower(req.http.host), 302);
        if (obj.status == 301) {
          set obj.response = "Moved Permanently";
        } else {
          set obj.response = "Found";
        }
        set obj.http.Location = table.lookup(redirect_locations, std.tolower(req.http.host), "");
        if (table.lookup_bool(redirect_preserve_urls, std.tolower(req.http.host), false)) {
          set obj.http.Location = obj.http.Location + req.url;
        }
        synthetic "";
        return (deliver);
      }
    VCL
  }
}

resource "fastly_tls_subscription" "main" {
  depends_on            = [fastly_service_vcl.cdn]
  domains               = [var.domain, "*.${var.domain}"]
  certificate_authority = "certainly"
}

resource "porkbun_dns_record" "domain_validation" {
  depends_on = [fastly_tls_subscription.main]
  for_each = {
    # Since the cert defines an apex (example.com) and a wildcard (*.example.com) domain, it will only return one challenge per domain
    for domain in fastly_tls_subscription.main.domains :
    replace(domain, "*.", "") => element([
      for obj in fastly_tls_subscription.main.managed_dns_challenges :
      obj if obj.record_name == "_acme-challenge.${replace(domain, "*.", "")}"
    ], 0)...
  }

  domain = regex("[^.]*\\.[^.]*$", each.value[0].record_name)
  subdomain = substr(
    each.value[0].record_name,
    0,
    length(each.value[0].record_name) - length(regex("[^.]*\\.[^.]*$", each.value[0].record_name)) - 1
  )
  type    = each.value[0].record_type
  content = each.value[0].record_value
  ttl     = 600
  prio    = 10
}

resource "fastly_tls_subscription_validation" "main" {
  subscription_id = fastly_tls_subscription.main.id
  depends_on      = [porkbun_dns_record.domain_validation]
}

data "fastly_tls_configuration" "default_tls" {
  default    = true
  depends_on = [fastly_tls_subscription_validation.main]
}

resource "porkbun_dns_record" "apex" {
  for_each = toset([for record in data.fastly_tls_configuration.default_tls.dns_records : record.record_value if record.record_type == "A"])

  domain    = var.domain
  subdomain = ""
  type      = "A"
  content   = each.value
  ttl       = 600
}

resource "porkbun_dns_record" "subdomain_redirect" {
  for_each = var.subdomain_redirects

  domain    = var.domain
  subdomain = each.key
  type      = "CNAME"
  content   = one([for record in data.fastly_tls_configuration.default_tls.dns_records : record.record_value if record.record_type == "CNAME"])
  ttl       = 600
}
